import type {Metadata} from "next";
import "./globals.css";
import {poppins} from "./fonts";

export const metadata: Metadata = {
	title: "Create Next App",
	description: "Generated by create next app",
};

export default function RootLayout({
	children,
}: Readonly<{
	children: React.ReactNode;
}>) {
	return (
		<html lang='ru'>
			<body className={poppins.className}>{children}</body>
		</html>
	);
}
